@startuml Pagelocs
  participant Requester
  participant PageLocsMgr
  control     MgrQueue
  participant ControlTask
  control     ControlQueue
  control     RetrieveQueue
  participant RetrieverTask

  ControlTask     <- PageLocsMgr : Setup
  RetrieverTask   <- ControlTask : Setup

  ControlQueue    <- PageLocsMgr : start(doc, first_item, item_count)
  ControlQueue    -> ControlTask : start_document(...)
  activate ControlTask

  note left
    The document retrieval 
    optimizes the order of 
    the items considering
    how the user interacts.
  end note
  loop All Items
    ControlTask     -> RetrieveQueue : retrieve(item)
    RetrieveQueue     -> RetrieverTask : retrieve(item)
    activate RetrieverTask
    RetrieverTask -> RetrieverTask : do item
    ControlQueue  <- RetrieverTask : item_retrieved(item)
    deactivate RetrieverTask
    ControlTask     <- ControlQueue : item_retrieved(item)
  end

  == Item already known ==
  Requester       -> PageLocsMgr: get_page_loc(item, offset)
  activate PageLocsMgr

  Requester       <- PageLocsMgr: got_it(start_offset, size)
  deactivate PageLocsMgr

  == Item needs to be retrieved (no yet in the list) ==

  Requester       -> PageLocsMgr: get_page_loc(item, offset)
  activate PageLocsMgr
  PageLocsMgr     -> ControlQueue : retrieve_asap(item)
  ControlQueue    -> ControlTask : retrieve_asap(item)

  ControlTask       -> RetrieveQueue : retrieve(item)
  RetrieveQueue       -> RetrieverTask : RETRIEVE_ITEM(item)
  activate RetrieverTask
  RetrieverTask   -> RetrieverTask : do item
  ControlQueue    <- RetrieverTask : item_retrieved(item)
  deactivate RetrieverTask
  ControlTask       <- ControlQueue : item_retrieved(item)


  PageLocsMgr     <- MgrQueue : got_asap(item)
  Requester       <- PageLocsMgr : got_it(start_offset, size) 
  deactivate PageLocsMgr

  MgrQueue        <- ControlTask : end_document()
  deactivate ControlTask
  RetrieveQueue   <- ControlTask : COMPLETED
  PageLocsMgr     <- MgrQueue : completed()
  
@enduml