@startuml
  participant Requester
  participant PageLocsMgr
  control     MgrQueue
  participant StateTask
  control     StateQueue
  control     RetrieveQueue
  participant RetrieverTask

  RetrieverTask   <- PageLocsMgr : Startup
  StateTask       <- PageLocsMgr : Startup

  StateQueue    <- PageLocsMgr : start(doc, first_item, item_count)
  StateQueue    -> StateTask : start_document(...)
  activate StateTask

  note left
    The document retrieval 
    optimizes the order of 
    the items considering
    how the user interacts.
  end note
  loop All Items
    StateTask     -> RetrieveQueue : retrieve(item)
    RetrieveQueue     -> RetrieverTask : retrieve(item)
    activate RetrieverTask
    RetrieverTask -> RetrieverTask : do item
    StateQueue  <- RetrieverTask : item_retrieved(item)
    deactivate RetrieverTask
    StateTask     <- StateQueue : item_retrieved(item)
  end

  == Item already known ==
  Requester       -> PageLocsMgr: get_page_loc(item, offset)
  activate PageLocsMgr

  Requester       <- PageLocsMgr: got_it(start_offset, size)
  deactivate PageLocsMgr

  == Item needs to be retrieved (no yet in the list) ==

  Requester       -> PageLocsMgr: get_page_loc(item, offset)
  activate PageLocsMgr
  PageLocsMgr     -> StateQueue : retrieve_asap(item)
  StateQueue    -> StateTask : retrieve_asap(item)

  StateTask       -> RetrieveQueue : retrieve(item)
  RetrieveQueue       -> RetrieverTask : retrieve(item)
  activate RetrieverTask
  RetrieverTask   -> RetrieverTask : do item
  StateQueue    <- RetrieverTask : item_retrieved(item)
  deactivate RetrieverTask
  StateTask       <- StateQueue : item_retrieved(item)


  MgrQueue        <- StateTask : got_asap(item)
  PageLocsMgr     <- MgrQueue : got_asap(item)
  Requester       <- PageLocsMgr : got_it(start_offset, size) 
  deactivate PageLocsMgr

  MgrQueue        <- StateTask : end_document()
  deactivate StateTask
  PageLocsMgr     <- MgrQueue : end_document()
  
@enduml