// Copyright (c) 2026 Guy Turcotte
//
// MIT License. Look at file licenses.txt for details.

// ---------------------------------------------------------------------------
//
// Page Locations Checker - A tool to verify the continuity of page offsets in a page locations
// file. This tool reads a page locations file generated by the PageLocs class, checks that the
// offsets are continuous for each itemref, and reports any discontinuities found.
//
// Usage: page_locs_checker <page_locs_file>
//
// ---------------------------------------------------------------------------

#include <cerrno>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iostream>
#include <map>
#include <string>
#include <utility>
#include <vector>

#define LOG_I(fmt, ...) { log('I', TAG, std::format(fmt, ## __VA_ARGS__).c_str());  }
#define LOG_D(fmt, ...) { log('D', TAG, std::format(fmt, ## __VA_ARGS__).c_str());  }
#define LOG_W(fmt, ...) { log('W', TAG, std::format(fmt, ## __VA_ARGS__).c_str());  }
#define LOG_V(fmt, ...) { log('V', TAG, std::format(fmt, ## __VA_ARGS__).c_str());  }
#define LOG_E(fmt, ...) { log('E', TAG, std::format(fmt, ## __VA_ARGS__).c_str());  }

void log(const char level, const char *tag, const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);

  fprintf(stderr, "%c %s: ", level, tag);
  vfprintf(stderr, fmt, args);
  fputc('\n', stderr);
  va_end(args);
}

static constexpr const int8_t LOCS_FILE_VERSION = 3;

static constexpr const char * TAG = "PageLocsChecker";

struct PageId {
  int16_t itemrefIndex{ 0 };
  int32_t offset{ 0 };
  PageId(int16_t idx, int32_t off) {
    itemrefIndex = idx;
    offset       = off;
  }
  PageId() = default;
};

struct PageInfo {
  int32_t size;
  int16_t pageNumber;
  PageInfo(int32_t siz, int16_t pageNbr) {
    size       = siz;
    pageNumber = pageNbr;
  }
  PageInfo() {};
};

struct PageCompare {
  auto operator()(const PageId &lhs, const PageId &rhs) const -> bool {
    if (lhs.itemrefIndex < rhs.itemrefIndex) { return true; }
    if (lhs.itemrefIndex > rhs.itemrefIndex) { return false; }
    return lhs.offset < rhs.offset;
  }
};

using PagePair = std::pair<const PageId, PageInfo>;
using PagesMap = std::map<PageId, PageInfo, PageCompare>;

PagesMap pagesMap;

#pragma pack(push, 1)
struct BookFormatParams {
  int8_t ident;       ///< Device identity (screen.hpp IDENT constant)
  int8_t orientation; ///< Config option only
  int8_t showTitle;
  int8_t showPictures;
  int8_t fontSize;
  int8_t lineHeight;
  int8_t useFontsInBook;
  int8_t font;
};
#pragma pack(pop)

BookFormatParams currentFormatParams;

int16_t          pageCount{ 0 };

bool readLocsFile(std::string filename) {
  std::ifstream file(filename, std::ios::in | std::ios::binary);

  LOG_D("Loading pages location from file {}.", filename);

  int8_t  version;
  int16_t pgCount;

  if (!file.is_open()) {
    LOG_I("Unable to open pages location file '{}': errno={} ({}). Calculating locations...",
          filename.c_str(), errno, std::strerror(errno));
    return false;
  }

  bool ok = false;

  while (true) {
    if (file.read(reinterpret_cast<char *>(&version), 1).fail()) { break; }
    if (version != LOCS_FILE_VERSION) { break; }

    if (file.read(reinterpret_cast<char *>(&currentFormatParams), sizeof(currentFormatParams))
        .fail()) {
      break;
    }
    if (file.read(reinterpret_cast<char *>(&pgCount), sizeof(pgCount)).fail()) { break; }

    pagesMap.clear();

    int16_t pageNbr = 0;

    for (int16_t i = 0; i < pgCount; ++i) {
      PageId   pageId;
      PageInfo pageInfo;

      if (file.read(reinterpret_cast<char *>(&pageId.itemrefIndex), sizeof(pageId.itemrefIndex))
          .fail()) {
        break;
      }
      if (file.read(reinterpret_cast<char *>(&pageId.offset), sizeof(pageId.offset)).fail()) { break; }
      if (file.read(reinterpret_cast<char *>(&pageInfo.size), sizeof(pageInfo.size)).fail()) { break; }
      pageInfo.pageNumber = (pageInfo.size >= 0) ? pageNbr++ : -1;

      //   if (pageNbr == 50) {
      //     pageInfo.size -= 1;
      //   }

      pagesMap.insert(std::pair(pageId, pageInfo));
    }

    pageCount = pageNbr;
    ok        = !file.fail();
    break;
  }

  file.close();

  if (!ok) {
    LOG_E("Page locations load failed for '{}' (fail={} bad={} eof={})", filename,
          file.fail() ? 1 : 0, file.bad() ? 1 : 0, file.eof() ? 1 : 0);
  }

  return ok;
}

void showPagesMap() {
  LOG_I("Pages Map:");
  for (const auto &entry : pagesMap) {
    const PageId &  id     = entry.first;
    const PageInfo &info = entry.second;
    LOG_I("ItemrefIndex: {}, Offset: {}, Size: {}, PageNumber: {}", id.itemrefIndex, id.offset,
          info.size, info.pageNumber);
  }
}

bool checkOffsetsContinuity() {

  bool result = true;

  // LOG_I("Checking offsets continuity...");

  int16_t currentItemrefIndex = -1;
  int32_t nextOffset          = -1;

  for (const auto &entry : pagesMap) {
    const PageId &  id     = entry.first;
    const PageInfo &info = entry.second;

    if (currentItemrefIndex != id.itemrefIndex) {
      nextOffset          = id.offset + info.size;
      currentItemrefIndex = id.itemrefIndex;
    } else {
      if (id.offset != nextOffset) {
        LOG_E("Offsets are not continuous at ItemrefIndex: {}, Offset: {}. Expected offset: {}",
              id.itemrefIndex, id.offset, nextOffset);
        result = false;
      }
      nextOffset = id.offset + info.size;
    }
  }

  return result;
}

int main(int argc, char *argv[]) {

  if (argc != 2) {
    LOG_E("Usage: {} <page_locs_file>", argv[0]);
    return 1;
  }

  if (!readLocsFile(argv[1])) {
    LOG_E("Failed to read page locs file: {}", argv[1]);
    return 1;
  }

  // showPagesMap();

  if (checkOffsetsContinuity()) {
    LOG_I("Offsets continuity check passed.");
  } else {
    LOG_E("Offsets continuity check failed.");
    return 1;
  }

  return 0;
}